from __future__ import annotations

from typing import ClassVar

from plugins.models.openai_compatible import OpenAICompatibleModel


class OpenAIModel(OpenAICompatibleModel):
    provider = "openai"
    base_url = "https://api.openai.com/v1"
    api_key_env = "OPENAI_API_KEY"
    pricing: ClassVar[dict[str, tuple[float, float]]] = {
        "gpt-4": (30.0, 60.0),
        "gpt-4-turbo": (10.0, 30.0),
        "gpt-4.1": (2.0, 8.0),
        "gpt-4.1-mini": (0.4, 1.6),
        "gpt-4.1-nano": (0.1, 0.4),
        "gpt-4o": (2.5, 10.0),
        "gpt-4o-2024-05-13": (5.0, 15.0),
        "gpt-4o-2024-08-06": (2.5, 10.0),
        "gpt-4o-2024-11-20": (2.5, 10.0),
        "gpt-4o-mini": (0.15, 0.6),
        "gpt-5": (1.25, 10.0),
        "gpt-5-mini": (0.25, 2.0),
        "gpt-5-nano": (0.05, 0.4),
        "gpt-5-pro": (15.0, 120.0),
        "gpt-5.1": (1.25, 10.0),
        "gpt-5.2": (1.75, 14.0),
        "gpt-5.2-chat-latest": (1.75, 14.0),
        "gpt-5.2-pro": (21.0, 168.0),
        "gpt-5.3-chat-latest": (1.75, 14.0),
        "gpt-5.3-codex": (1.75, 14.0),
        "gpt-5.3-codex-spark": (1.75, 14.0),
        "gpt-5.4": (2.5, 15.0),
        "gpt-5.4-mini": (0.75, 4.5),
        "gpt-5.4-nano": (0.2, 1.25),
        "gpt-5.4-pro": (30.0, 180.0),
        "gpt-5.5": (5.0, 30.0),
        "gpt-5.5-pro": (30.0, 180.0),
        "gpt-5.6": (4.0, 20.0),
        "gpt-5.6-luna": (0.2, 1.2),
        "gpt-5.6-sol": (4.0, 20.0),
        "gpt-5.6-terra": (2.0, 12.0),
        "gpt-6-astra": (10.0, 50.0),
        "gpt-6-luna": (0.1, 0.5),
        "gpt-6-sol": (2.0, 10.0),
        "o1": (15.0, 60.0),
        "o1-pro": (150.0, 600.0),
        "o3": (2.0, 8.0),
        "o3-mini": (1.1, 4.4),
        "o3-pro": (20.0, 80.0),
        "o4-mini": (1.1, 4.4),
    }
    descriptions: ClassVar[dict[str, str]] = {
        "gpt-4": "GPT model for general reasoning, writing, coding, and tool-assisted",
        "gpt-4-turbo": "Compact GPT model for low-latency assistance and high-volume w",
        "gpt-4.1": "Long-lived GPT workhorse for coding, instruction following, and pr",
        "gpt-4.1-mini": "Affordable GPT-4.1 lane for fast coding help and structured e",
        "gpt-4.1-nano": "Tiny GPT-4.1 option for classification, routing, and very hig",
        "gpt-4o": "capable general-purpose model",
        "gpt-4o-2024-05-13": "GPT model for general reasoning, writing, coding, and to",
        "gpt-4o-2024-08-06": "GPT model for general reasoning, writing, coding, and to",
        "gpt-4o-2024-11-20": "GPT model for general reasoning, writing, coding, and to",
        "gpt-4o-mini": "fast and cheap; simple tasks",
        "gpt-5": "Original GPT-5 workhorse for reasoning, coding, writing, and tool wo",
        "gpt-5-mini": "Small GPT-5 for responsive agents, coding help, and everyday au",
        "gpt-5-nano": "Tiny GPT-5 lane for routing, extraction, classification, and bu",
        "gpt-5-pro": "Higher-accuracy GPT-5 tier for tough analysis, coding reviews, a",
        "gpt-5.1": "Sharper GPT-5 generation for coding, product work, and tool-assist",
        "gpt-5.2": "Reliable GPT generation for broad coding, writing, and tool-assist",
        "gpt-5.2-chat-latest": "Chat-tuned GPT model for conversational assistance, wr",
        "gpt-5.2-pro": "Higher-accuracy GPT-5.2 variant for tougher reasoning and revi",
        "gpt-5.3-chat-latest": "Chat-tuned GPT model for conversational assistance, wr",
        "gpt-5.3-codex": "Coding-optimized GPT model for repository edits, reviews, an",
        "gpt-5.3-codex-spark": "Coding-optimized GPT model for repository edits, revie",
        "gpt-5.4": "Agent-ready GPT for coding and computer-use workflows at a lower c",
        "gpt-5.4-mini": "Strong small GPT for coding subagents, quick tool use, and hi",
        "gpt-5.4-nano": "Cheapest GPT-5.4 lane for simple routing, extraction, and bul",
        "gpt-5.4-pro": "More exact GPT-5.4 tier for demanding professional reasoning a",
        "gpt-5.5": "Default frontier GPT for coding, computer use, research, and knowl",
        "gpt-5.5-pro": "Highest-accuracy GPT-5.5 tier for slower, precision-heavy reas",
        "gpt-5.6": "Frontier GPT-5.6 model for complex professional work, coding, and",
        "gpt-5.6-luna": "Cost-efficient GPT-5.6 model for fast, high-volume workloads",
        "gpt-5.6-sol": "Frontier GPT-5.6 model for complex professional work, coding,",
        "gpt-5.6-terra": "Balanced GPT-5.6 model for capable, cost-efficient everyday",
        "gpt-6-astra": "GPT-6 Astra is OpenAI's most capable model for complex reasoni",
        "gpt-6-luna": "OpenAI's most efficient model for focused, high-volume tasks",
        "gpt-6-sol": "OpenAI model for complex coding and agentic workflows",
        "o1": "O-series reasoning model for hard analysis, math, coding, and planning",
        "o1-pro": "O-series reasoning model for hard analysis, math, coding, and plann",
        "o3": "Deliberate o-series reasoner for hard math, coding, and multi-step anal",
        "o3-mini": "Smaller o-series reasoner for economical coding, math, and plannin",
        "o3-pro": "High-effort o3 tier for difficult technical reasoning and careful a",
        "o4-mini": "Fast o-series model for compact reasoning, coding, and tool use",
    }
